### ISSUE TITLE
Invalid email addresses accepted despite docs saying they won't be

### ISSUE THREAD

**Issue by americrypt** [nodemailer/smtp-server#149]

**Comment by andris9** [comment]
Any examples of such addresses? smtp-server accepts addresses that are valid **by smtp syntax**, it does not care if the address is otherwise valid (does the host exist or not etc). This is intentional to allow building servers for internal traffic with local addresses. For actual internet-compatible validation you might want to use something like [@hapi/address](https://hapi.dev/module/address/api/?v=4.0.1#emailisvalidemail-options)

**Comment by americrypt** [comment]
@andris9 It would help greatly if you would allow people to finish editing their comments before you close their issue. This issue was open less than 5 minutes sir, please, I cannot type that damn fast.
